services:
  wireghost:
    build: .
    volumes:
      - ./output:/data/output
    network_mode: host

  nmap:
    image: instrumentisto/nmap:latest
    volumes:
      - ./output:/data/output
    network_mode: host
    profiles: ["tools"]

  nuclei:
    image: projectdiscovery/nuclei:latest
    volumes:
      - ./output:/data/output
    network_mode: host
    profiles: ["tools"]

  httpx:
    image: projectdiscovery/httpx:latest
    volumes:
      - ./output:/data/output
    network_mode: host
    profiles: ["tools"]
