# Generated by Django 6.0.4 on 2026-04-15 18:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('auth', 'Authentication'), ('scan', 'Scan'), ('report', 'Report'), ('admin', 'Admin'), ('config', 'Configuration')], default='admin', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='up', max_length=20)),
                ('ports_count', models.IntegerField(default=0)),
                ('findings_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('report_title', models.CharField(default='Vulnerability Assessment Report', max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('logo_path', models.CharField(blank=True, max_length=500)),
                ('brand_color', models.CharField(default='#006D38', max_length=7)),
                ('include_cover', models.BooleanField(default=True)),
                ('include_executive_summary', models.BooleanField(default=True)),
                ('include_target_subnets', models.BooleanField(default=True)),
                ('include_live_hosts', models.BooleanField(default=True)),
                ('include_open_ports', models.BooleanField(default=True)),
                ('include_findings', models.BooleanField(default=True)),
                ('include_evidence', models.BooleanField(default=True)),
                ('default_formats', models.CharField(default='dashboard,docx,xlsx', max_length=100)),
                ('disclaimer', models.TextField(default='This report is confidential and intended solely for the use of the organization to which it is addressed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('setup_complete', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_by', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'scanner_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('scopes', models.CharField(default='scans:read,findings:read', max_length=500)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(default='open', max_length=20)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('service_product', models.CharField(blank=True, max_length=200)),
                ('service_version', models.CharField(blank=True, max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.host')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=500)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('parallelism', models.IntegerField(default=10)),
                ('timeout', models.IntegerField(default=3600)),
                ('report_formats', models.CharField(default='dashboard,html,docx,xlsx', max_length=100)),
                ('version_detect', models.BooleanField(default=True)),
                ('os_detect', models.BooleanField(default=True)),
                ('service_enum', models.BooleanField(default=True)),
                ('skip_nuclei', models.BooleanField(default=False)),
                ('skip_openvas', models.BooleanField(default=True)),
                ('hosts_count', models.IntegerField(default=0)),
                ('ports_count', models.IntegerField(default=0)),
                ('findings_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('output_dir', models.CharField(blank=True, max_length=500)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanner.scan')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanner.scan'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('host_ip', models.GenericIPAddressField(null=True)),
                ('port', models.CharField(blank=True, max_length=10)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('full_url', models.CharField(blank=True, max_length=1000)),
                ('template_id', models.CharField(blank=True, max_length=200)),
                ('cve', models.CharField(blank=True, max_length=500)),
                ('cwe', models.CharField(blank=True, max_length=200)),
                ('cvss', models.CharField(blank=True, max_length=200)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('curl_command', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.host')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanPolicy',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration')], default='full', max_length=20)),
                ('parallelism', models.IntegerField(default=10)),
                ('timeout', models.IntegerField(default=3600)),
                ('port_range', models.CharField(default='1-65535', max_length=500)),
                ('tools', models.JSONField(default=dict)),
                ('version_detect', models.BooleanField(default=True)),
                ('os_detect', models.BooleanField(default=True)),
                ('severity_filter', models.CharField(default='all', max_length=100)),
                ('report_formats', models.CharField(default='dashboard,docx,xlsx', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], max_length=20)),
                ('time', models.TimeField()),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration')], default='full', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanpolicy')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='scanner.host')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('theme_mode', models.CharField(default='dark', max_length=20)),
                ('accent_color', models.CharField(default='blue', max_length=20)),
                ('font_size', models.CharField(default='default', max_length=20)),
                ('notif_scan_complete', models.BooleanField(default=True)),
                ('notif_scan_failed', models.BooleanField(default=True)),
                ('notif_critical_finding', models.BooleanField(default=True)),
                ('notif_report_ready', models.BooleanField(default=True)),
                ('notif_weekly_digest', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
