# Generated by Django 6.0.4 on 2026-04-11 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='up', max_length=20)),
                ('ports_count', models.IntegerField(default=0)),
                ('findings_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(default='open', max_length=20)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('service_product', models.CharField(blank=True, max_length=200)),
                ('service_version', models.CharField(blank=True, max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.host')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=500)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('parallelism', models.IntegerField(default=10)),
                ('timeout', models.IntegerField(default=3600)),
                ('report_formats', models.CharField(default='dashboard,html,docx,xlsx', max_length=100)),
                ('version_detect', models.BooleanField(default=True)),
                ('os_detect', models.BooleanField(default=True)),
                ('service_enum', models.BooleanField(default=True)),
                ('skip_nuclei', models.BooleanField(default=False)),
                ('skip_openvas', models.BooleanField(default=True)),
                ('hosts_count', models.IntegerField(default=0)),
                ('ports_count', models.IntegerField(default=0)),
                ('findings_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('output_dir', models.CharField(blank=True, max_length=500)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanner.scan')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanner.scan'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('host_ip', models.GenericIPAddressField(null=True)),
                ('port', models.CharField(blank=True, max_length=10)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('full_url', models.CharField(blank=True, max_length=1000)),
                ('template_id', models.CharField(blank=True, max_length=200)),
                ('cve', models.CharField(blank=True, max_length=500)),
                ('cwe', models.CharField(blank=True, max_length=200)),
                ('cvss', models.CharField(blank=True, max_length=200)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('curl_command', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.host')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='scanner.host')),
            ],
        ),
    ]
