# Generated by Django 6.0.4 on 2026-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_seed_default_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='nuclei_default_templates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='nuclei_templates',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
