# Generated by Django 6.0.4 on 2026-04-18 07:06

import django.db.models.deletion
import scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_permission_site_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='scanner_ass_last_se_bc83a8_idx',
            old_name='scanner_ass_last_se_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='scanner_ass_first_s_080088_idx',
            old_name='scanner_ass_first_s_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='scanner_ass_status_f14d40_idx',
            old_name='scanner_ass_status_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='scanner_ass_risk_sc_20c593_idx',
            old_name='scanner_ass_risk_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='scanner_ass_ip_6318f0_idx',
            old_name='scanner_ass_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='scanner_rol_role_1a0569_idx',
            old_name='scanner_rol_role_idx',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['user', 'revoked_at'], name='scanner_api_user_id_00561b_idx'),
        ),
    ]
