# Generated by Django 6.0.4 on 2026-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='default_parallelism',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='default_report_formats',
            field=models.CharField(default='dashboard,docx,xlsx', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='default_timeout',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_shared_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
