# Generated by Django 6.0.4 on 2026-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_telegram_and_general_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_unresponsive',
            field=models.BooleanField(default=False),
        ),
    ]
