# Generated by Django 6.0.4 on 2026-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_userpreference_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
