# Generated by Django 6.0.4 on 2026-04-28 17:15

import django.db.models.deletion
import scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_scheduled_scan_stop_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaBackupCode',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMfaConfig',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
