# Generated by Django 6.0.4 on 2026-05-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0024_alter_exploitmatch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='skip_nikto',
            field=models.BooleanField(default=False),
        ),
    ]
