# Generated by Django 6.0.4 on 2026-05-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0025_add_skip_nikto'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='skip_netexec',
            field=models.BooleanField(default=False),
        ),
    ]
