# Generated by Django 6.0.4 on 2026-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0027_remove_scan_skip_openvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
