# Generated by Django 6.0.4 on 2026-05-18 06:44

import django.db.models.deletion
import scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0028_add_mac_vendor_to_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADReconSession',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('authenticated', 'Authenticated'), ('unauth', 'Unauthenticated')], default='authenticated', max_length=16)),
                ('dc_ip', models.GenericIPAddressField()),
                ('domain', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('tool_status', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ADGroup',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('sam_account_name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('members', models.JSONField(default=list)),
                ('member_count', models.IntegerField(default=0)),
                ('admin_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADDomain',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('netbios_name', models.CharField(blank=True, max_length=64)),
                ('sid', models.CharField(blank=True, max_length=256)),
                ('functional_level', models.CharField(blank=True, max_length=64)),
                ('forest', models.CharField(blank=True, max_length=256)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADComputer',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('dns_hostname', models.CharField(blank=True, max_length=256)),
                ('os', models.CharField(blank=True, max_length=256)),
                ('os_version', models.CharField(blank=True, max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('last_logon', models.DateTimeField(blank=True, null=True)),
                ('member_of', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADCertService',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('ca_name', models.CharField(max_length=256)),
                ('host', models.CharField(blank=True, max_length=256)),
                ('templates', models.JSONField(default=list)),
                ('vulnerable_template', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_services', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADACL',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('object_dn', models.CharField(max_length=512)),
                ('identity', models.CharField(max_length=256)),
                ('active_directory_rights', models.CharField(max_length=256)),
                ('access_control_type', models.CharField(max_length=64)),
                ('interesting_rights', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADShare',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('access', models.CharField(blank=True, max_length=256)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADSPN',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=256)),
                ('sam_account_name', models.CharField(max_length=256)),
                ('host', models.CharField(blank=True, max_length=256)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spns', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADTrust',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_domain', models.CharField(max_length=256)),
                ('target_domain', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=32)),
                ('trust_type', models.CharField(max_length=64)),
                ('transitive', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='ADUser',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('sam_account_name', models.CharField(max_length=256)),
                ('upn', models.CharField(blank=True, max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('admin_count', models.IntegerField(default=0)),
                ('last_logon', models.DateTimeField(blank=True, null=True)),
                ('member_of', models.JSONField(default=list)),
                ('pwd_last_set', models.DateTimeField(blank=True, null=True)),
                ('spn_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='scanner.adreconsession')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialProfile',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.TextField()),
                ('nt_hash', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='adreconsession',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.credentialprofile'),
        ),
    ]
