# Generated by Django 6.0.5 on 2026-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0035_increase_target_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adacl',
            options={'ordering': ['object_dn']},
        ),
        migrations.AlterModelOptions(
            name='adcertservice',
            options={'ordering': ['ca_name']},
        ),
        migrations.AlterModelOptions(
            name='adcomputer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='addomain',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='adgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='adshare',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='adspn',
            options={'ordering': ['service_name']},
        ),
        migrations.AlterModelOptions(
            name='adtrust',
            options={'ordering': ['source_domain', 'target_domain']},
        ),
        migrations.AlterModelOptions(
            name='aduser',
            options={'ordering': ['sam_account_name']},
        ),
        migrations.AlterField(
            model_name='finding',
            name='matched_at',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='finding',
            name='script_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='service_source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
