# Generated by Django 6.0.5 on 2026-05-25 14:00

import django.db.models.deletion
from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0036_ad_model_tweaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanArtifact',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('content_type', models.CharField(default='text/plain', max_length=32)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='scanner.host')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='scanner.scan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['scan', 'tool'], name='scanner_scanartifact_scan_tool_idx'),
                    models.Index(fields=['host'], name='scanner_scanartifact_host_idx'),
                ],
            },
        ),
    ]
