# Generated by makemigrations; written to host filesystem because container
# /app/ is read-only.

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0038_fix_scanartifact_index_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration'), ('discovery', 'Host Discovery'), ('phase_based', 'Phase-Based Scan')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='phases',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of enabled phase names for phase-based scans'),
        ),
        migrations.AddField(
            model_name='scan',
            name='current_phase_index',
            field=models.IntegerField(default=-1, help_text='0-based index of the currently executing/completed phase'),
        ),
        migrations.AlterField(
            model_name='scanpolicy',
            name='scan_type',
            field=models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration'), ('discovery', 'Host Discovery'), ('phase_based', 'Phase-Based Scan')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledscan',
            name='scan_type',
            field=models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('port', 'Port Scan Only'), ('web', 'Web Application Scan'), ('service', 'Service Enumeration'), ('discovery', 'Host Discovery'), ('phase_based', 'Phase-Based Scan')], default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='PhaseRun',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('discovery', 'Discovery'), ('portscan', 'Port Scan'), ('webdetect', 'Web Detect'), ('webcrawl', 'Web Crawl'), ('vulnscan', 'Vulnerability Scan'), ('enumeration', 'Enumeration')], max_length=20)),
                ('sequence', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('tool_config', models.JSONField(default=dict)),
                ('output_summary', models.JSONField(default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('scan', models.ForeignKey(on_delete=models.CASCADE, related_name='phase_runs', to='scanner.scan')),
            ],
            options={
                'ordering': ['scan', 'sequence'],
                'unique_together': {('scan', 'phase')},
            },
        ),
    ]
