# Generated by Django 6.0.4 on 2026-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0042_merge_0040_host_discovered_by_0041_add_scan_skip_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='dashboard_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
