# Generated by Django 6.0.4 on 2026-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0043_add_dashboard_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomputer',
            name='dn',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='dn',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='aduser',
            name='dn',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
