# Generated by Django 6.0.4 on 2026-07-15 09:30

import django.db.models.deletion
import scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0045_add_spray_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLFinding',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('object_dn', models.CharField(max_length=1024)),
                ('principal', models.CharField(max_length=512)),
                ('right_name', models.CharField(max_length=256)),
                ('right_type', models.CharField(max_length=32)),
                ('is_inherited', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('attack_path', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_findings', to='scanner.adreconsession')),
            ],
            options={
                'ordering': ['-risk_level', 'object_dn', 'principal'],
            },
        ),
        migrations.CreateModel(
            name='CredentialFinding',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('gpp_password', 'GPP Password (cpassword)'), ('gpp_autologin', 'GPP Auto-login'), ('laps', 'LAPS Password'), ('user_desc', 'User Description'), ('user_info', 'User Info Field'), ('unix_password', 'UnixUserPassword Attribute'), ('user_password', 'UserPassword Attribute'), ('spider_plus', 'SMB Share Spider')], max_length=32)),
                ('credential_type', models.CharField(choices=[('cleartext', 'Cleartext Password'), ('ntlm_hash', 'NTLM Hash'), ('laps', 'LAPS Password')], default='cleartext', max_length=16)),
                ('target', models.CharField(blank=True, max_length=512)),
                ('username', models.CharField(max_length=256)),
                ('password', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_findings', to='scanner.adreconsession')),
            ],
            options={
                'ordering': ['source', 'username'],
            },
        ),
        migrations.CreateModel(
            name='VulnCheck',
            fields=[
                ('id', models.UUIDField(default=scanner.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=256)),
                ('vulnerable', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_checks', to='scanner.adreconsession')),
            ],
            options={
                'ordering': ['-vulnerable', 'check_name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'check_name', 'host'), name='uq_vuln_check_session_host')],
            },
        ),
    ]
